name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyinstaller
      run: |
        python tools/create_package.py --exiftool Image-ExifTool-11.97.tar.gz
    - name: Upload generated executable
      uses: actions/upload-artifact@v4
      with:
        name: cfm.mac-amd64
        path: dist/cfm
